terminal = "alacritty"

corner_radius = "3"
border_size = "3"

term_opacity = "0.75"
font_size = "12.0"

mod = "SUPER"

icon_theme = "Suru++"

dmenu = "/usr/bin/wofi -d"

bg_dim = "#232A2E"
bg0 = "#2D353B"
bg1 = "#343F44"
bg2 = "#3D484D"
bg3 = "#475258"
bg4 = "#4F585E"
bg5 = "#56635f"
bg_visual = "#543A48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3A515D"
bg_yellow = "#4D4C43"

fg = "#D3C6AA"
red = "#E67E80"
orange = "#E69875"
yellow = "#DBBC7F"
green = "#A7C080"
aqua = "#83C092"
blue = "#7FBBB3"
purple = "#D699B6"
grey0 = "#7A8478"
grey1 = "#859289"
grey2 = "#9DA9A0"

bg_diml = "#EFEBD4"
bg3l = "#E6E2CC"
bg4l = "#E0DCC7"
fgl = "#5C6A72"

bg_dim_hypr = "rgb(232A2E)"
bg0_hypr = "rgb(2D353B)"
bg1_hypr = "rgb(343F44)"
bg2_hypr = "rgb(3D484D)"
bg3_hypr = "rgb(475258)"
bg4_hypr = "rgb(4F585E)"
bg5_hypr = "rgb(56635f)"
bg_visual_hypr = "rgb(543A48)"
bg_reg_hypr = "rgb(514045)"
bg_green_hypr = "rgb(425047)"
bg_blue_hypr = "rgb(3A515D)"
bg_yellow_hypr = "rgb(4D4C43)"

fg_hypr = "rgb(D3C6AA)"
red_hypr = "rgb(E67E80)"
orange_hypr = "rgb(E69875)"
yellow_hypr = "rgb(DBBC7F)"
green_hypr = "rgb(A7C080)"
aqua_hypr = "rgb(83C092)"
blue_hypr = "rgb(7FBBB3)"
purple_hypr = "rgb(D699B6)"
grey0_hypr = "rgb(7A8478)"
grey1_hypr = "rgb(859289)"
grey2_hypr = "rgb(9DA9A0)"
