position = "top"
height = 30

start = [
    { type = "workspaces", name_map = { Discord = "󰙯", "special:Spotify" = "󰓇", Mail = "", Steam="󰓓" }, hidden = [ "special:Spotify" ], all_monitors = true}
]

center = [
    { type = "clock", format = "%I:%M %p %a %e %b %y", format_popup = "%I:%M %p"}
]

end = [
    { type = "music", format = "{title}", show_status_icon = false },
    #{ type = "custom", name="volume", bar = [{type = "progress", max = 1, orientation="v", length=200, value = "wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -oe '[[:digit:]]\\.[[:digit:]]\\{2\\}'" }]},
    { type = "clipboard" },
    { type = "tray" }
]
