# -*- conf -*-

term=foot

font=monospace:size={{font_size}}

pad=5x5

[colors-dark]
alpha={{term_opacity}}
# alpha-mode=default # Can be `default`, `matching` or `all`
background={{bg0_foot}}
foreground={{fg_foot}}

regular0={{bg3_foot}}  # black
regular1={{red_foot}}  # red
regular2={{green_foot}}  # green
regular3={{yellow_foot}}  # yellow
regular4={{blue_foot}}  # blue
regular5={{purple_foot}}  # magenta
regular6={{aqua_foot}}  # cyan
regular7={{fg_foot}} # white
bright0={{bg2_foot}}   # bright black
bright1={{red_foot}}   # bright red
bright2={{green_foot}}   # bright green
bright3={{yellow_foot}}   # bright yellow
bright4={{blue_foot}}   # bright blue
bright5={{purple_foot}}   # bright magenta
bright6={{aqua_foot}}   # bright cyan
bright7={{fg_foot}}   # bright white

[key-bindings]
spawn-terminal=Control+Shift+Enter

# vim: ft=dosini
